[package]
name = "parseit"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
serde = { version = "1.0", features = ["derive"] }
toon-format = "0.3"
clap = { version = "4.4", features = ["derive"] }

[profile.release]
strip = true
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"
